use_frameworks!

target 'ELWaterdeclines_Example' do
  pod 'ELWaterdeclines', :path => '../'

  target 'ELWaterdeclines_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
